// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5stsPnuNPMICVH1toJXfI3UHHxUjilf8',
    appId: '1:523147600498:web:e5094e1cd72fa7100d98eb',
    messagingSenderId: '523147600498',
    projectId: 'fir-5fd66',
    authDomain: 'fir-5fd66.firebaseapp.com',
    storageBucket: 'fir-5fd66.firebasestorage.app',
    measurementId: 'G-3MMG5DJ9XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdMmYT0S2-Y9rS_OnJ3KKfxlYxQm04Iiw',
    appId: '1:523147600498:android:2e9dbc92ecea66fb0d98eb',
    messagingSenderId: '523147600498',
    projectId: 'fir-5fd66',
    storageBucket: 'fir-5fd66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjaRgvV3WO9QqznVSGBWZFJ05uXvAYms',
    appId: '1:523147600498:ios:38f43ad50c47f4c00d98eb',
    messagingSenderId: '523147600498',
    projectId: 'fir-5fd66',
    storageBucket: 'fir-5fd66.firebasestorage.app',
    iosBundleId: 'com.example.docway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjaRgvV3WO9QqznVSGBWZFJ05uXvAYms',
    appId: '1:523147600498:ios:38f43ad50c47f4c00d98eb',
    messagingSenderId: '523147600498',
    projectId: 'fir-5fd66',
    storageBucket: 'fir-5fd66.firebasestorage.app',
    iosBundleId: 'com.example.docway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5stsPnuNPMICVH1toJXfI3UHHxUjilf8',
    appId: '1:523147600498:web:b4ce7fdfb162a2210d98eb',
    messagingSenderId: '523147600498',
    projectId: 'fir-5fd66',
    authDomain: 'fir-5fd66.firebaseapp.com',
    storageBucket: 'fir-5fd66.firebasestorage.app',
    measurementId: 'G-81EPB74LXK',
  );
}
